spring:
  application:
    name: spring-boot-actuator-demo

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,health
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}